### ISSUE TITLE
Error from module mechanize

### ISSUE THREAD

**Issue by ibnusyawall** [pirmansx/mbf#2]
<pre>
Traceback (most recent call last):
  File "MBF.py", line 324, in <module>
    menu()
  File "MBF.py", line 319, in menu
    idteman()
  File "MBF.py", line 279, in idteman
    login()
  File "MBF.py", line 243, in login
    nama = br.find_link(url_regex='logout.php').text
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/mechanize/_mechanize.py", line 777, in find_link
    raise LinkNotFoundError()
mechanize._mechanize.LinkNotFoundError
</pre>

An error occurred while retrieving a friend id in this script

**Comment by SSU12** [comment]
Itu kenapa ya bang kok gw juga kekgitu

**Comment by SSU12** [comment]
Cara balikin nya gmna
